version: "2"
run:
  concurrency: 4
  issues-exit-code: 8
  tests: false
output:
  path-prefix: ""
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - prealloc
    - revive
    - staticcheck
    - tagliatelle
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  uniq-by-line: false
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
